### Tasks

* 1. Download a small dataset of IPL cricket player stats (e.g., runs, wickets, matches, strike rate) and apply StandardScaler from scikit-learn to scale all numeric features. Save the scaled data to a new CSV file named ipl_scaled.csv.

In [71]:
import pandas as pd

In [72]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 4\ipl_players.csv")

In [73]:
df.head()

        Player_Name  Runs  Wickets  Matches  Strike_Rate
0       Virat Kohli   741        0       15        154.7
1   Ruturaj Gaikwad   583        0       14        141.2
2    Jasprit Bumrah    15       20       16         85.0
3      Sunil Narine   488       17       15        180.7
4  Heinrich Klaasen   479        0       16        171.1

In [74]:
num_cols = ['Runs', 'Wickets', 'Matches', 'Strike_Rate']

In [75]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [76]:
df[num_cols] = scaler.fit_transform(df[num_cols])

In [77]:
df.to_csv("ipl_scaled.csv")

In [78]:
df.head()

        Player_Name      Runs   Wickets   Matches  Strike_Rate
0       Virat Kohli  1.668280 -0.728464  0.430331     0.235686
1   Ruturaj Gaikwad  0.914525 -0.728464 -0.430331    -0.122016
2    Jasprit Bumrah -1.795178  1.495853  1.290994    -1.611114
3      Sunil Narine  0.461317  1.162206  0.430331     0.924592
4  Heinrich Klaasen  0.418382 -0.728464  1.290994     0.670227

* 2. Using a dataset of Flipkart product ratings (features: price, rating, number of reviews, discount), apply MinMaxScaler so that all features are scaled between 0 and 1. Print the minimum and maximum value for each column before and after scaling.

Hint: Use pandas to load the data and scikit-learn's MinMaxScaler for scaling.

In [79]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 4\flipkart_products.csv")

In [80]:
df.head()

   Price  Rating  Number_of_Reviews  Discount
0  12999     4.3              12050        15
1  54999     4.6               4500        10
2    749     3.8                120        50
3   1299     4.1                850        60
4   2499     4.0               2100        45

In [81]:
cols = ['Price', 'Rating', 'Number_of_Reviews', 'Discount']

In [82]:
print("Before Scaling\n")

for columns in cols:
    print(f"{columns}")
    print("Min :", df[columns].min())
    print("Max :", df[columns].max())
    print()

Before Scaling

Price
Min : 649
Max : 54999

Rating
Min : 3.5
Max : 4.7

Number_of_Reviews
Min : 80
Max : 15300

Discount
Min : 8
Max : 70

In [83]:
from sklearn.preprocessing import MinMaxScaler          #Formula of MinMaxScaler = X - X(min) / X(max)-X(min)

scaler = MinMaxScaler()

df[cols] = scaler.fit_transform(df[cols])

In [84]:
df.head()

      Price    Rating  Number_of_Reviews  Discount
0  0.227231  0.666667           0.786465  0.112903
1  1.000000  0.916667           0.290407  0.032258
2  0.001840  0.250000           0.002628  0.677419
3  0.011960  0.500000           0.050591  0.838710
4  0.034039  0.416667           0.132720  0.596774

In [85]:
print("After Scaling\n")

for columns in cols:
    print(f"{columns}")
    print("Min :", df[columns]. min())
    print("Max :", df[columns]. max())
    print()

After Scaling

Price
Min : 0.0
Max : 1.0

Rating
Min : 0.0
Max : 1.0

Number_of_Reviews
Min : 0.0
Max : 1.0

Discount
Min : 0.0
Max : 0.9999999999999999

* 3. Given a Spotify songs dataset (features: danceability, energy, tempo, popularity), use correlation analysis to select the top 2 features most related to 'popularity'. List the selected features and explain your choice in one line each.

In [86]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 4\spotify_songs.csv")

In [87]:
df.head()

   Danceability  Energy  Tempo  Popularity
0          0.72    0.65    120          85
1          0.85    0.88    128          92
2          0.55    0.40     95          45
3          0.62    0.72    115          68
4          0.78    0.82    130          88

In [88]:
features = ['Danceability', 'Energy', 'Tempo']

In [89]:
corr = df[features + ['Popularity']].corr()
corr

              Danceability    Energy     Tempo  Popularity
Danceability      1.000000  0.338560  0.174903    0.922973
Energy            0.338560  1.000000  0.954610    0.625115
Tempo             0.174903  0.954610  1.000000    0.491640
Popularity        0.922973  0.625115  0.491640    1.000000

In [105]:
corr_with_target = corr['Popularity'].drop('Popularity')
corr_with_target

Danceability    0.922973
Energy          0.625115
Tempo           0.491640
Name: Popularity, dtype: float64

In [91]:
top_features = corr_with_target.sort_values(ascending=False).head(2)

In [92]:
print("Top 2 Features:\n\n", top_features)

Top 2 Features:

 Danceability    0.922973
Energy          0.625115
Name: Popularity, dtype: float64

* 4. Take a Zomato restaurant dataset and use scikit-learn's RFE (Recursive Feature Elimination) with a DecisionTreeRegressor to select the 3 most important features for predicting 'average cost for two'. List the selected features and the RFE ranking.

In [93]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 4\zomato_restaurants.csv")

In [94]:
df.head()

,Rating,Votes,Online_Order,Table_Booking,Delivery_Time,Average_Cost_For_Two
0,4.2,1200,1,0,30,800
1,4.5,2500,1,1,25,1800
2,3.8,150,0,0,45,400
3,4.1,850,1,0,35,600
4,4.0,600,1,0,40,500

In [95]:
X = df.drop('Average_Cost_For_Two', axis=1)
y = df['Average_Cost_For_Two']

In [96]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_selection import RFE

model = DecisionTreeRegressor(random_state=42)

rfe = RFE(estimator=model, n_features_to_select=3)      # RFE = find the most important features (feature selection technique)

rfe.fit(X,y)

RFE(estimator=DecisionTreeRegressor(random_state=42), n_features_to_select=3)

In [97]:
selected_features = X.columns[rfe.support_]
print("Selected Features:\n", selected_features)

Selected Features:
 Index(['Rating', 'Votes', 'Table_Booking'], dtype='str')

In [98]:
print("RFE Ranking:")

for feature, rank in zip(X.columns, rfe.ranking_):
    print(feature, ":", rank)

RFE Ranking:
Rating : 1
Votes : 1
Online_Order : 2
Table_Booking : 1
Delivery_Time : 3

* 5. Given a BookMyShow movie ratings dataset, detect outliers in the 'user ratings' column using the IQR method. Remove the outliers and display how many rows were dropped.

Hint: Calculate Q1, Q3, and IQR; filter out rows outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR].

In [99]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 4\bookmyshow_ratings.csv")

In [100]:
df.head()

  Movie_Name  User_Ratings
0    Movie_1           8.2
1    Movie_2           7.5
2    Movie_3           8.8
3    Movie_4           6.9
4    Movie_5           7.1

In [ ]:
col = 'User_Ratings'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


df_clean = df[
    (df[col] >= lower_bound) &
    (df[col] <= upper_bound)
]

rows_dropped = len(df) - len(df_clean)

print("\nOriginal Rows:", len(df))
print("Rows After Removing Outliers:", len(df_clean))
print("Rows Dropped:", rows_dropped)

print(df_clean.head())

Q1: 7.25
Q3: 8.45
IQR: 1.1999999999999993

Original Rows: 23
Rows After Removing Outliers: 20
Rows Dropped: 3
  Movie_Name  User_Ratings
0    Movie_1           8.2
1    Movie_2           7.5
2    Movie_3           8.8
3    Movie_4           6.9
4    Movie_5           7.1